[workspace]
members = [
	"fixed-hash",
	"keccak-hash",
	"kvdb",
	"kvdb-memorydb",
	"kvdb-rocksdb",
	"kvdb-shared-tests",
	"axia-bytes",
	"rlp",
	"rlp-derive",
	"uint",
	"axia-util-mem",
	"primitive-types",
	"ethereum-types",
	"ethbloom",
	"axia-util-mem/derive"
]
